### PR TITLE
Fall 2022 NOAA NMFS cohorts (WIP)

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
@jules32 This PR has 4 Events. With your answers to these items, I will propagate to all 4 events:
- what email for "Contact Openscapes: openscapes at nceas.ucsb.edu"
- Please suggest edits to "This opportunity is funded and coordinated by.." e.g. if you want to refer to NMFS-wide coordination
- See Quarto-style citation example in NWFSC paragraph 1 (Lowndes et al). How I can cite your blog post (https://blogs.scientificamerican.com/observations/open-software-means-kinder-science) Quarto-style, since it doesn't have a DOI?
  - pls suggest any changes and I'll update the other cohort event pages

I'll merge these **after** Tidepool Sep 15th.

**Comment by jules32** [comment]
Hi @stefaniebutland , I've pushed a commit with answers to your questions for NWFSC. I think now you'll be good to go! Thank you!

**Review by jules32 — COMMENTED** [review]
my changes are included in my commit. thanks!

**Comment by stefaniebutland** [comment]
All your edits are propagated to the 4 events. Thanks so much @jules32. 
I'm going to merge on Monday instead of Friday afternoon in case I run into trouble. (Rendered posts looked good but still being cautious).

**Pull request merged**
