### PR TITLE
create ESIP 2023 event post

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
@jules32 I don't see you or Amy on the speakers lists at the extra links you provided. Added them to the post of course though

**Review by jules32 — COMMENTED** [review]
this looks good Stef, thank you!

**Comment by stefaniebutland** [comment]
Adding speakers now!

**Comment by jules32** [comment]
I think sched defaults speakers only as session organizers, I'll request to update after we meet tomorrow

**Comment by stefaniebutland** [comment]
added speaker bios to Jan 26 event post - copied from our Google doc

**Pull request merged**
