### PR TITLE
create rstudio::conf keynote event

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
This PR addresses https://github.com/Openscapes/how_we_work/issues/149

banner image is 520x520, but in the events list page, it appears to take up extra vertical space 🤔

**Comment by jules32** [comment]
Hi Stef, ah - the 520x520 sizing is for thumbnails on the openscapes.org (blogdown) website, not for the events (quarto) website. For the quarto site, it's better for it to be horizontally rectangular. Do you want to give that a try?

**Comment by stefaniebutland** [comment]
@jules32 rectangular banner is better. I'll add note to Events page README
Happy to make any text edits

**Comment by jules32** [comment]
Thank you @stefaniebutland this is perfect!

**Pull request merged**
